# LLM model
api_key: ""
model_id: "dvue-aoai-001-gpt-4.1"
temperature: 1.0

# TritonBench
statis_path: "~/TB-eval/TritonBench/data/TritonBench_G_v1.json"
py_folder: "~/TB-eval/TritonBench/data/TritonBench_G_v1"
instruction_path: "~/TB-eval/TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
corpus_path: "./dataloaders/TB_eval/train_crawl.json"
golden_metrics: "~/TB-eval/TritonBench/performance_metrics/perf_G/golden_metrics"
perf_ref_folder: "~/TB-eval/TritonBench/performance_metrics/perf_G/golden_results"
perf_G_path: "~/TB-eval/TritonBench/performance_metrics/perf_G"
py_interpreter: "python"
result_path: null
mem_file: null
start_iter: 0

output_path: "../outputs/reflexion_oneshot_gpt41.jsonl"
max_iteration: 20
multi_thread: true
